"""empty message

Revision ID: 4445c5ecb758
Revises: 67858cd84a08
Create Date: 2020-05-13 20:03:31.741155

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4445c5ecb758'
down_revision = '67858cd84a08'
branch_labels = None
depends_on = None

ICONS = {
    "travel": "⛱",
    "study": "🏫",
    "work": "🏢",
    "relocate": "🚜",
    "programming": "🎮"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('icon', sa.String(length=30), nullable=True))
    for slug, icon in ICONS.items():
        op.execute(f"UPDATE goals SET icon = \'{icon}\' WHERE slug = \'{slug}\'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'icon')
    # ### end Alembic commands ###
